format = """
$directory$git_branch$git_status$python$lua$golang$rust$cmd_duration
$character"""

add_newline = true
palette = 'tokyonight_night'

[directory]
style = 'bold fg:neon_cyan'
format = '[$path]($style) '
truncation_length = 3
truncation_symbol = '.../'
truncate_to_repo = false

[directory.substitutions]
'~' = ' '
'.config' = '󰒓'
'Desktop' = ' '
'Programming' = ' '

[character]
success_symbol = '[❯](bold fg:neon_blue) '
error_symbol = '[❯](bold fg:neon_pink) '

[git_branch]
style = 'fg:neon_purple bold'
symbol = ''
format = '[$branch]($style) '

[git_status]
ahead = '⇡${count}'
behind = '⇣${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
untracked = '?${count}'
modified = '!${count}'
conflicted = '=${count}'
staged = '+${count}'
stashed = '*${count}'
deleted = '-${count}'
style = 'fg:neon_orange bold'
format = '[$all_status$ahead_behind]($style) '

[python]
style = 'fg:python_blue bold'
symbol = ''
format = '[$symbol]($style) '

[lua]
style = 'fg:lua_blue bold'
symbol = ''
format = '[$symbol]($style) '

[rust]
style = 'fg:rust_orange bold'
symbol = ''
format = '[$symbol]($style) '

[golang]
style = 'fg:go_blue bold'
symbol = "\U000f07d3"  # "󰟓 "
format = '[$symbol]($style) '

[cmd_duration]
min_time = 500
style = 'fg:soft_gray'
format = '[$duration]($style) '

[palettes.tokyonight_night]
blue = '#7aa2f7'
cyan = '#7dcfff'
green = '#9ece6a'
orange = '#ff9e64'
purple = '#bb9af7'
red = '#f7768e'
yellow = '#e0af68'
gray = '#627e97'
white = '#cbe0f0'
black = '#011628'
neon_blue = '#82aaff'
neon_cyan = '#86e1fc'
neon_purple = '#c099ff'
neon_pink = '#ff7ab8'
neon_orange = '#ffb86c'
neon_yellow = '#ffd866'
soft_gray = '#7f96aa'
python_blue = '#3776ab'
lua_blue = '#51a0cf'
rust_orange = '#dea584'
go_blue = '#00add8'
